### ISSUE TITLE
Error installing ansible in VM master with ansible 2.8.X+

### ISSUE THREAD

**Issue by micafer** [grycap/im#1039]

**Comment by micafer** [comment]
Possibly related with the change of options to context.CLIARGS.
https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.8.html

**Comment by micafer** [comment]
This is the full error:
```py
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/task_executor.py", line 145, in run
    res = self._execute()
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/task_executor.py", line 650, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/action/__init__.py", line 917, in _execute_module
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/action/__init__.py", line 1062, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/connection/ssh.py", line 1188, in exec_command
    cmd = self._build_command(*args)
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/connection/ssh.py", line 584, in _build_command
    if self._play_context.verbosity > 3:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```
