### ISSUE TITLE
 Error creating node: 409 Conflict Multiple possible networks found, use a Network ID to be more specific

### ISSUE THREAD

**Issue by belavicm** [grycap/im#1211]
Centos 7
IM 1.10.5

IM log:
```2021-09-01 08:16:03,348 - CloudConnector - ERROR - Inf ID: 158706f2-0a5e-11ec-8204-fa163ecf9ae1: Error creating node: 409 Conflict Multiple possible networks found, use a Network ID to be more specific..
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/IM/connectors/OpenStack.py", line 1182, in launch
    node = driver.create_node(**args)
  File "/usr/local/lib/python3.8/dist-packages/libcloud/compute/drivers/openstack.py", line 1458, in create_node
    resp = self.connection.request("/servers",
  File "/usr/local/lib/python3.8/dist-packages/libcloud/common/openstack.py", line 232, in request
    return super(OpenStackBaseConnection, self).request(action=action,
  File "/usr/local/lib/python3.8/dist-packages/libcloud/common/base.py", line 655, in request
    response = responseCls(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/libcloud/compute/drivers/openstack.py", line 1186, in __init__
    super(OpenStack_1_1_Response, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/libcloud/common/base.py", line 165, in __init__
    raise exception_from_message(code=self.status,
libcloud.common.exceptions.BaseHTTPError: 409 Conflict Multiple possible networks found, use a Network ID to be more specific.
```
https://github.com/grycap/im/blob/4e097b80a6a5e58d6fb3216c24699a69cbb98b0d/IM/connectors/OpenStack.py#L983 return empty list because https://github.com/grycap/im/blob/4e097b80a6a5e58d6fb3216c24699a69cbb98b0d/IM/connectors/OpenStack.py#L940 is never true...

**Solution**
Change https://github.com/grycap/im/blob/4e097b80a6a5e58d6fb3216c24699a69cbb98b0d/IM/connectors/OpenStack.py#L940 to 
``if net_map[i].name not in nets:``

**Comment by micafer** [comment]
Hi @belavicm,

Could you set the input file you have used to create the infrastructure?
And also Could you set the list of networks and floating ip pools of the OpenStack site?

Thanks.

**Comment by belavicm** [comment]
[ssds_centos.txt](https://github.com/grycap/im/files/7104161/ssds_centos.txt)
[ssds_sge.txt](https://github.com/grycap/im/files/7104162/ssds_sge.txt)

I add some self.log_info() into .../IM/connectors/OpenStack.py
```
def get_networks(self, driver, radl):
        nets = []
        pool_names = [pool.name for pool in driver.ex_list_floating_ip_pools()]
        self.log_info("pool_names: %s" % pool_names)
        get_subnets, ost_nets = self.get_ost_network_info(driver, pool_names)
        self.log_info("get_subnets: %s" % get_subnets)
        self.log_info("ost_nets: %s" % ost_nets)
        if get_subnets:
            net_map = self.map_networks(radl, ost_nets)
            self.log_info("net_map: %s" % net_map)
            # First set the public ones
            for public in [True, False]:
                i = 0
                while radl.systems[0].getValue("net_interface." + str(i) + ".connection"):
                    net_name = radl.systems[0].getValue("net_interface." + str(i) + ".connection")
                    network = radl.get_network_by_id(net_name)
                    self.log_info("public: %s" % public)
                    self.log_info("net_name: %s" % net_name)
                    self.log_info("network: %s" % network)
                    if public == network.isPublic():
                        if net_map[i]:
                            network.setValue('provider_id', net_map[i].name)
                            if net_map[i].name not in pool_names:
                                nets.append(net_map[i])
                                self.log_info("net_map[i].name: %s" % net_map[i].name)
                    i += 1
            self.log_info("nets: %s" % nets)
```
Output:
```
2021-09-03 07:45:51,865 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: pool_names: ['isabella', 'crongi-private', 'crongi-public', 'crongi-srce-private']
2021-09-03 07:45:52,132 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: get_subnets: True
2021-09-03 07:45:52,132 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: ost_nets: [<OpenStackNetwork id="3e3b4275-63a2-4dcb-8c48-bb6d0583331b" name="isabella" cidr="maskIP/24">, <OpenStackNetwork id="55116a6e-f7f8-45c0-87f5-2ace22120dda" name="crongi-private" cidr="maskIP/21">, <OpenStackNetwork id="74174dfa-38b4-4734-8099-f0a1606018ab" name="srce-vxlan" cidr="192.168.100.0/24">, <OpenStackNetwork id="8e13ccd5-69d8-4bb5-bf45-19c36a134d88" name="crongi-public" cidr="maskIP/23">, <OpenStackNetwork id="bec3bbe3-f140-4826-8e42-2a109793d36d" name="jupyterhub-vxlan" cidr="192.168.100.0/22">, <OpenStackNetwork id="e7a636e2-90a6-43b7-84bf-8b1fc2743926" name="crongi-srce-private" cidr="maskIP/23">]
2021-09-03 07:45:52,133 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: net_map: {0: <OpenStackNetwork id="e7a636e2-90a6-43b7-84bf-8b1fc2743926" name="crongi-srce-private" cidr="maskIP/23">}
2021-09-03 07:45:52,133 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: public: True
2021-09-03 07:45:52,133 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: net_name: private
2021-09-03 07:45:52,133 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: network: network private ( provider_id = 'crongi-srce-private' and
sg_name = 'ec3' )
2021-09-03 07:45:52,133 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: public: False
2021-09-03 07:45:52,133 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: net_name: private
2021-09-03 07:45:52,133 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: network: network private ( provider_id = 'crongi-srce-private' and
sg_name = 'ec3' )
2021-09-03 07:45:52,133 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: nets: []
2021-09-03 07:45:55,199 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: Creating node
2021-09-03 07:45:56,164 - CloudConnector - ERROR - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: Error creating node: 409 Conflict Multiple possible networks found, use a Network ID to be more specific..
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/IM/connectors/OpenStack.py", line 1183, in launch
    node = driver.create_node(**args)
  File "/usr/local/lib/python3.8/dist-packages/libcloud/compute/drivers/openstack.py", line 1458, in create_node
    resp = self.connection.request("/servers",
  File "/usr/local/lib/python3.8/dist-packages/libcloud/common/openstack.py", line 232, in request
    return super(OpenStackBaseConnection, self).request(action=action,
  File "/usr/local/lib/python3.8/dist-packages/libcloud/common/base.py", line 655, in request
    response = responseCls(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/libcloud/compute/drivers/openstack.py", line 1186, in __init__
    super(OpenStack_1_1_Response, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/libcloud/common/base.py", line 165, in __init__
    raise exception_from_message(code=self.status,
libcloud.common.exceptions.BaseHTTPError: 409 Conflict Multiple possible networks found, use a Network ID to be more specific.
```

Output with ``if net_map[i].name not in nets:`` :

```
2021-09-03 07:51:46,114 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: pool_names: ['isabella', 'crongi-private', 'crongi-public', 'crongi-srce-private']
2021-09-03 07:51:46,351 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: get_subnets: True
2021-09-03 07:51:46,351 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: ost_nets: [<OpenStackNetwork id="3e3b4275-63a2-4dcb-8c48-bb6d0583331b" name="isabella" cidr="maskIP/24">, <OpenStackNetwork id="55116a6e-f7f8-45c0-87f5-2ace22120dda" name="crongi-private" cidr="maskIP/21">, <OpenStackNetwork id="74174dfa-38b4-4734-8099-f0a1606018ab" name="srce-vxlan" cidr="192.168.100.0/24">, <OpenStackNetwork id="8e13ccd5-69d8-4bb5-bf45-19c36a134d88" name="crongi-public" cidr="maskIP/23">, <OpenStackNetwork id="bec3bbe3-f140-4826-8e42-2a109793d36d" name="jupyterhub-vxlan" cidr="192.168.100.0/22">, <OpenStackNetwork id="e7a636e2-90a6-43b7-84bf-8b1fc2743926" name="crongi-srce-private" cidr="maskIP/23">]
2021-09-03 07:51:46,351 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: net_map: {0: <OpenStackNetwork id="e7a636e2-90a6-43b7-84bf-8b1fc2743926" name="crongi-srce-private" cidr="maskIP/23">}
2021-09-03 07:51:46,351 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: public: True
2021-09-03 07:51:46,351 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: net_name: private
2021-09-03 07:51:46,351 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: network: network private ( provider_id = 'crongi-srce-private' and
sg_name = 'ec3' )
2021-09-03 07:51:46,351 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: public: False
2021-09-03 07:51:46,352 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: net_name: private
2021-09-03 07:51:46,352 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: network: network private ( provider_id = 'crongi-srce-private' and
sg_name = 'ec3' )
2021-09-03 07:51:46,352 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: net_map[i].name: crongi-srce-private
2021-09-03 07:51:46,352 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: nets: [<OpenStackNetwork id="e7a636e2-90a6-43b7-84bf-8b1fc2743926" name="crongi-srce-private" cidr="maskIP">]
2021-09-03 07:51:47,446 - InfrastructureManager - INFO - Getting information about the Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1
2021-09-03 07:51:49,074 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: Creating node
2021-09-03 07:51:50,365 - CloudConnector - INFO - Inf ID: 99b1e84e-0c88-11ec-a107-fa163ecf9ae1: Node successfully created.
```

**Comment by micafer** [comment]
Could you show the list of networks of the site (showing the "External") attribute?

**Comment by belavicm** [comment]
List of networks:
```$ openstack network list --long
+--------------------------------------+---------------------+--------+----------------------------------+-------+--------+--------------------------------------+--------------+-------------+--------------------+------+
| ID                                   | Name                | Status | Project                          | State | Shared | Subnets                              | Network Type | Router Type | Availability Zones | Tags |
+--------------------------------------+---------------------+--------+----------------------------------+-------+--------+--------------------------------------+--------------+-------------+--------------------+------+
| 3e3b4275-63a2-4dcb-8c48-bb6d0583331b | isabella            | ACTIVE | dd3e00c87f4347efa741e746b7e7037b | UP    | False  | 22ba4d7b-adf6-4275-982c-b08a6abaee0a | flat         | External    | nova               |      |
| 55116a6e-f7f8-45c0-87f5-2ace22120dda | crongi-private      | ACTIVE | dd3e00c87f4347efa741e746b7e7037b | UP    | True   | bffc522e-aab3-4fa5-ab4e-2b2e03982085 | flat         | External    | nova               |      |
| 8e13ccd5-69d8-4bb5-bf45-19c36a134d88 | crongi-public       | ACTIVE | dd3e00c87f4347efa741e746b7e7037b | UP    | True   | d5b468e5-949a-415c-9ee6-9c5e380da774 | flat         | External    | nova               |      |
| e7a636e2-90a6-43b7-84bf-8b1fc2743926 | crongi-srce-private | ACTIVE | dd3e00c87f4347efa741e746b7e7037b | UP    | False  | 79588c24-259c-490f-94a8-8b299acf65b1 | flat         | External    | nova               |      |
+--------------------------------------+---------------------+--------+----------------------------------+-------+--------+--------------------------------------+--------------+-------------+--------------------+------+```

**Comment by micafer** [comment]
The problem is not so easy to solve in a general case.
In your case the problem is that all your networks are maked as "External",  so they are considered as "Floating IP pools" that should not be attached on VM boot.
Is this configuration correct?

**Comment by nakos** [comment]
I'd like to add that in the EGI FedCloud there are some openstack sites that produce the same error when we try to deploy a VM using the AppDB VMOps dashboard. We always request one public network (outbound='yes') without any other property. We also tried providing the provider_id name in RADL ([radl_example.txt](https://github.com/grycap/im/files/7144261/radl_example.txt)), but still got back the same results. 

When we applied the specific patch that @belavicm proposed, we stopped receiving the error and some of the deployments where successful and acquired an IP (others failed for different reasons, quota exceeded etc). 

All of the specific sites have only one external router and one or more internal ones. The IM version we use is 1.10.4

**Comment by micafer** [comment]
Hi @nakos ,
Could you tell me the name of one site that produces the same error?
I want to reproduce the error in this sites.
Regards.

**Comment by nakos** [comment]
Hi @micafer,

below are two sites that produce the error, but with the patch they work as expected:

IISAS-FedCloud (cloud.ui.savba.sk) tested with project ID 71dc9c3785cc4876bfb1a4bfc681e0f3 (vo.access.egi.eu)
TR-FC1-ULAKBIM (bulut.truba.gov.tr) tested with project ID 2fa316a05d364de9b5a55ac78a45f8bf (vo.access.egi.eu)

**Comment by micafer** [comment]
Hi @nakos ,

In you case you always have to add a private network:
```
network __PUBLIC_NETWORK__ (
  outbound = 'yes'
)

network __PRIVATE_NETWORK__ (
)

system EGI_Ubuntu_20_04 (
  instance_name = 'EGI_Ubuntu_20_04' and
  cpu.count = 1 and
  memory.size = 2048M and
  disks.free_size >= 10G and
  disk.0.size = 10G and
  disk.0.image.url = '...' and
  net_interface.1.connection = '__PUBLIC_NETWORK__' and
  net_interface.0.connection = '__PRIVATE_NETWORK__'
)


deploy EGI_Ubuntu_20_04 1
```

**Comment by belavicm** [comment]
> The problem is not so easy to solve in a general case.
> In your case the problem is that all your networks are maked as "External", so they are considered as "Floating IP pools" that should not be attached on VM boot.
> Is this configuration correct?

Thanks @micafer, using vxlan (Internal network) works without error.
