### ISSUE TITLE
Unable to deploy on OpenStack using IM 1.7.3 & 1.7.4

### ISSUE THREAD

**Issue by alahiff** [grycap/im#653]
I'm able to successfully deploy VMs on OpenStack clouds with IM 1.7.2 and below. However, with more recent versions, I get this error:
```
2018-07-11 11:37:16,320 - InfrastructureManager - ERROR - Error Creating Inf.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/IM/ServiceRequests.py", line 118, in _execute
    res = self._call_function()
  File "/usr/local/lib/python2.7/dist-packages/IM/ServiceRequests.py", line 243, in _call_function
    async_call)
  File "/usr/local/lib/python2.7/dist-packages/IM/InfrastructureManager.py", line 1333, in CreateInfrastructure
    raise e
LibcloudError: <LibcloudError in None 'Invalid scheme:  in url None'>
```
The entry in the authorization file looks like this:
```
id = ost1; type = OpenStack; host = https://cloud.name:5000/v2.0; username = username; password = password; tenant = tenant; base_url = https://cloud.name:8774/v2/xxxxxxxx
```

**Comment by alahiff** [comment]
Closing this, I managed to get things to work. Sorry!
