### ISSUE TITLE
Error in ctxt process

### ISSUE THREAD

**Issue by micafer** [grycap/im#703]
```
Traceback (most recent call last):
  File "/var/tmp/.im/d20cbc0e-dce4-11e8-8843-0a580af4018e//ctxt_agent.py", line 680, in <module>
    if CtxtAgent.run(options.general[0], options.vmconf[0]):
  File "/var/tmp/.im/d20cbc0e-dce4-11e8-8843-0a580af4018e//ctxt_agent.py", line 665, in run
    res_data = CtxtAgent.contextualize_vm(general_conf_data, vm_conf_data)
  File "/var/tmp/.im/d20cbc0e-dce4-11e8-8843-0a580af4018e//ctxt_agent.py", line 547, in contextualize_vm
    cred_used = CtxtAgent.wait_ssh_access(vm)
  File "/var/tmp/.im/d20cbc0e-dce4-11e8-8843-0a580af4018e//ctxt_agent.py", line 155, in wait_ssh_access
    success, res = CtxtAgent.test_ssh(vm, vm_ip, remote_port)
  File "/var/tmp/.im/d20cbc0e-dce4-11e8-8843-0a580af4018e//ctxt_agent.py", line 124, in test_ssh
    return success, res
UnboundLocalError: local variable 'res' referenced before assignment
```

**Comment by micafer** [comment]
Fixed in commit: 19010c35153c50266bc105b72a5ed1a14251a6cd
