### ISSUE TITLE
Issues with Ansible 2.8

### ISSUE THREAD

**Issue by micafer** [grycap/im#844]

**Comment by micafer** [comment]
```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/jenkins/workspace/grycap/im-unit/test/unit/test_ansible.py", line 42, in test_ansible_thread
    ansible_process.run()
  File "/home/jenkins/workspace/grycap/im-unit/IM/ansible_utils/ansible_launcher.py", line 133, in run
    self.result.put((0, self.launch_playbook_v2(), output))
  File "/home/jenkins/workspace/grycap/im-unit/IM/ansible_utils/ansible_launcher.py", line 244, in launch_playbook_v2
    loader, inventory, variable_manager = self.get_play_prereqs(options)
  File "/home/jenkins/workspace/grycap/im-unit/IM/ansible_utils/ansible_launcher.py", line 143, in get_play_prereqs
    return self.get_play_prereqs_2_4(options)
  File "/home/jenkins/workspace/grycap/im-unit/IM/ansible_utils/ansible_launcher.py", line 179, in get_play_prereqs_2_4
    variable_manager.extra_vars = self.extra_vars
AttributeError: can't set attribute
```

**Comment by micafer** [comment]
Now there is another error:
```
TASK [Get Facts] **************************************************************************************************************************
Thursday 23 May 2019  10:46:17.987237 
fatal: [10.0.0.1]: FAILED! => {"msg": "the connection plugin '<class 'ansible.utils.sentinel.Sentinel'>' was not found"}

```

**Comment by micafer** [comment]
Untill I can find a solution I set ansible < 2.8.0 as dependency.
