### ISSUE TITLE
Error loading infra data from DB 

### ISSUE THREAD

**Issue by micafer** [grycap/im#917]
This error appears

```
Traceback (most recent call last):
  File "/home/micafer/codigo/git_im/im.tosca/IM/InfrastructureList.py", line 202, in _get_data_from_db
    inf = IM.InfrastructureInfo.InfrastructureInfo.deserialize(data)
  File "/home/micafer/codigo/git_im/im.tosca/IM/InfrastructureInfo.py", line 158, in deserialize
    dic['radl'] = parse_radl(dic['radl'])
  File "/home/micafer/codigo/git_im/im.tosca/radl/radl_parse.py", line 383, in parse_radl
    return parser.parse(data)
  File "/home/micafer/codigo/git_im/im.tosca/radl/radl_parse.py", line 359, in parse
    return self.yacc.parse(data, tracking=True, debug=0, lexer=self.lexer)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 331, in parse
    return self.parseopt(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 909, in parseopt
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python2.7/dist-packages/ply/yacc.py", line 192, in call_errorfunc
    r = errorfunc(token)
  File "/home/micafer/codigo/git_im/im.tosca/radl/radl_parse.py", line 354, in p_error
    raise RADLParseException("Parse error in: " + str(t), line=t.lineno if t else None)
RADLParseException: Line 279: Parse error in: LexToken(NUMBER,5,279,10018)
```

It is a problem generated by the IM when generating deployment groups.
In particular the error is:

```
deploy node 1 1cloudname
```

If the cloudid has a number as the first char the RADL parser gets it as a number and returns a parser error.

**Comment by micafer** [comment]
I have to check the format of the id in the auth data and return an error in case of starting with a number.
